# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    utility_class:
        class: CRM\ToolsBundle\Service\utility
    check_file_class:
        class: CRM\ToolsBundle\Service\checkFile
    refresh_button_analysis:
        class: CRM\ToolsBundle\Service\refreshAnalysis
        arguments: ['@doctrine']

    ldap:
           class: 'Symfony\Component\Ldap\LdapClient'
           arguments:
               - 172.18.0.50    # host
               - 389			# port
               - 3				# version
               - false			# SSL
               - false			# TLS
    user.form.user_role:
       class: CRM\UserBundle\Form\UserType
       arguments: ['%security.role_hierarchy.roles%']
       tags:
           - { name: form.type }
    user.user_provider:
       class: CRM\UserBundle\Entity\UserProvider
       arguments: ['@doctrine.orm.entity_manager']



