crm_tools_authenticate:
    path:     /
    defaults:  { _controller: CRMUserBundle:Security:login }

crm_tools_homepage:
    path:      /home_page
    defaults: { _controller: CRMToolsBundle:Default:index }

crm_tools_graph:
    path:     /graphs_performance
    defaults: { _controller: CRMToolsBundle:Monitoring:graph }

crm_log_errors:
    path:     /log_errors
    defaults: { _controller: CRMToolsBundle:Monitoring:logErrors }

crm_errors_analysis:
    path:     /errors_analysis
    defaults: { _controller: CRMToolsBundle:DataQuality:errorsAnalysis}

crm_reload_request:
    path:     /reload_request/{query_id}
    defaults: { _controller: CRMToolsBundle:DataQuality:reloadRequest }

crm_file_upload:
    path:     /file_upload
    defaults: { _controller: CRMToolsBundle:FileIntegration:fileUpload }

crm_file_delete:
    path:     /file_delete/{file_id}/{file_name}
    defaults: { _controller: CRMToolsBundle:FileIntegration:deleteFile }

crm_business_view:
    path:     /business_view
    defaults: { _controller: CRMToolsBundle:FileIntegration:businessView }

crm_total_campaigns:
    path:     /total_compaigns
    defaults: { _controller: CRMToolsBundle:CrmWeather:totalCompaigns }

crm_contact_creation:
    path:     /contact_creation
    defaults: { _controller: CRMToolsBundle:CrmWeather:contactCreation }

crm_retargeting_monitoring:
    path:     /retargeting_monitoring
    defaults: { _controller: CRMToolsBundle:CrmWeather:retargetingMonitoring }

crm_game_integration:
    path:     /game_integration
    defaults: { _controller: CRMToolsBundle:CrmWeather:gameIntegration }

crm_contact_form:
    path:     /contact_form
    defaults: { _controller: CRMToolsBundle:UcrSearchEngine:contactForm }

crm_booking_form:
    path:     /booking_form
    defaults: { _controller: CRMToolsBundle:UcrSearchEngine:bookingForm }

crm_ldap_connect:
    path:     /ldap_connect
    defaults: { _controller: CRMToolsBundle:Default:ldapConnect }


