crm_tools_homepage:
    path:     /
    defaults: { _controller: CRMToolsBundle:Default:index }

crm_tools_graph:
    path:     /graphs_performance
    defaults: { _controller: CRMToolsBundle:Monitoring:graph }

crm_logs_view:
    path:     /logs_view
    defaults: { _controller: CRMToolsBundle:Monitoring:contact }

crm_errors_analysis:
    path:     /errors_analysis
    defaults: { _controller: CRMToolsBundle:DataQuality:errorsAnalysis}

crm_tools_display:
    path:     /display
    defaults: { _controller: CRMToolsBundle:DataQuality:useProcess }

crm_reload_request:
    path:     /reload_request/{query_id}
    defaults: { _controller: CRMToolsBundle:DataQuality:reloadRequest }

crm_file_upload:
    path:     /file_upload
    defaults: { _controller: CRMToolsBundle:FileIntegration:fileUpload }

crm_file_delete:
    path:     /file_delete/{file_id}/{file_name}
    defaults: { _controller: CRMToolsBundle:FileIntegration:deleteFile }

crm_business_view:
    path:     /business_view
    defaults: { _controller: CRMToolsBundle:FileIntegration:businessView }

crm_total_campaigns:
    path:     /total_compaigns
    defaults: { _controller: CRMToolsBundle:CrmWeather:totalCompaigns }

crm_contact_creation:
    path:     /contact_creation
    defaults: { _controller: CRMToolsBundle:CrmWeather:contactCreation }

crm_retargeting_monitoring:
    path:     /retargeting_monitoring
    defaults: { _controller: CRMToolsBundle:CrmWeather:retargetingMonitoring }

crm_game_integration:
    path:     /game_integration
    defaults: { _controller: CRMToolsBundle:CrmWeather:gameIntegration }

crm_contact_booking:
    path:     /contact_booking_forms
    defaults: { _controller: CRMToolsBundle:UcrSearchEngine:contactBookingForms }




